### ISSUE TITLE
Remove unicode characters from page title

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/enciv-home#25]
If you go to this link, https://enciv.org/posts/american-democracy-still-strong-at-the-roots and hover over the browser's tab for this page, the title has &#8211; in it.  That's because the - in the page title is unicode.

To fix this, in app/web-components/article.js  use ReactHelmet to set the title of the page to the title of the article with unicode mapped to printable characters - or just removed.   The title is in the subject. 

See stackoverflow for options on converting unicode to ascii.

**Comment by baraahmad** [comment]
@ddfridley Hi David, I would like to try this.
