### ISSUE TITLE
TextBlock with Icon

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/enciv-home#34]
Modify app/components/text-block to accept an icon prop. and a side prop.

- [ ] If the icon prop is not provided, it works as it does now.

If the icon prop is provided,

- [ ] use the side prop, (default left) to decide which side to put the text on
- [ ] In full width mode, the text will be in 75% and the icon will be in 25%
- [ ] In condensed mode, the icon should be on top, and centered, and the text below.
- [ ] the icon will be ReactComponent
- [ ] copy the icon out of figma and create a file for it in assets/svg
- [ ] create additional stories in stories/text-block.stories.js for testing this. 
- [ ] add another block in stories/home.stories.js to show this

[Figma](https://www.figma.com/design/enAOpp07bF6ZhuXXw13Ttx/EnCiv?node-id=31-216&t=GvWBviIyUqKu4XCO-4)
![Image](https://github.com/EnCiv/enciv-home/assets/3317487/78e63ab0-57ee-4cee-9493-73a2c579d4e6)
__Note the red vertical line is just a reference line, not part of the component.__

**Comment by justin-b-yee** [comment]
Hi @ddfridley: 

Would it be alright if I take this issue on? I'm currently unable to self-assign.
