### ISSUE TITLE
VideoBlock

### ISSUE THREAD

**Issue by ddfridley** [EnCiv/enciv-home#6]
```
<VideoBlock
    className=""
    mode: "" // dark, white  see top-nav-bar.jsx for differences
    subject: ""  // if not present do not render the div
    actionText: ""
    action: "" | ()=>{}  // url for an anchor, or function to execute onClick
    videoUrl: ""
>
```
[Figma](https://www.figma.com/file/Kh21xXYttgD8P2jG1acf1f/enciv-website-redesign?type=design&node-id=463-4284&mode=design&t=ELer0tYuHoI4xPZ7-4)

![Image](https://github.com/EnCiv/enciv-home/assets/3317487/971dab8f-7888-4e5b-b7a3-468bf2136fea)

- [x] Create stories for smartphone and desktop
- [x] user this video for testing: https://youtu.be/Tb2u0h_IUGc
- [x] requires #8 

New Requirements to stitch it into the home page:

- [x] Add video block to app/web-components/home.js as another entry in Blocks called VideoBlock.
- [x] Add a VideoBlock example into to the story for stories/home.stories.js - between two 'TextBlock' s

**Comment by WangYufeng1990** [comment]
Hi David, I would like to try this.

**Comment by WangYufeng1990** [comment]
Got it, thanks

**Comment by WangYufeng1990** [comment]
Hi David, I met a issue when I try using "git push -u origin short-issue-text#issue-number" to push the code for Video block. It asked me to enter username and password for github, but after I did that, I got a message said "remote: Support for password authentication was removed on August 13, 2021." That really werid, actually I have login my github account in my IDEA.

**Comment by ddfridley** [comment]
@WangYufeng1990 I just added 2 new requirements to this issue for adding the video block into the home story.  Should be fun to see how it all plays together.

**Comment by WangYufeng1990** [comment]
@ddfridley got the requirements change and working on it.

**Comment by ddfridley** [comment]
@WangYufeng1990 how is this going, I know you've got another one going on but I don't want to lose track on this one. Thanks.

**Comment by WangYufeng1990** [comment]
@ddfridley Sorry for the delay. I just pushed the new code in videoBlock branch. I tried the thing in our conversation (change height), but the videoblock component looks werid in webpage. So I used useEffect to handle the video container size. This looks good.
